server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
  tomcat:
    threads:
      max: 50                       # 최대 스레드 수
      min-spare: 5                  # 최소 스레드 수
    connection-timeout: 10000       # 10초 연결 타임아웃
spring:
  cache:
    type: simple
    cache-names: userRecommendations
  config:
    import: optional:application-data.yml

  profiles:
    active: prod
    include: oauth
  cors:
    allowed-origins: http://3.34.91.104:8080,https://onmarket.duckdns.org,http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  codec:
    max-in-memory-size: 10MB
  mvc:
    async:
      request-timeout: -1 # 응답 대기 시간 연장

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # 허용 파일 크기
      max-request-size: 50MB   # 요청 본문 총합



springdoc:
  packages-to-scan: com.onmarket
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui-onmarket.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

  security:
    user:
      name: test
      password: 1234